version: '3.4'

services:
  puppeteer-server:
    image: puppeteer-server
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 3000
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      MAPBOX_ID: ${MAPBOX_ID}
      OPEN_GRAPH_BUCKET_NAME: ${OPEN_GRAPH_BUCKET_NAME}
      CRYPTO_INTERNAL_AES_GCM_KEY: ${CRYPTO_INTERNAL_AES_GCM_KEY}
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    command: ['npm', 'run', 'dev']
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 3001:6379
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
